### ISSUE TITLE
Question: Is the support for generating tracing JITs planned

### ISSUE THREAD

**Issue by 6D65** [nbp/holyjit#12]
Hi,

I'm trying to understand the scope of the project. Was wondering if the generating Tracing JITs(sort of like RPython) is in the plans.

As far as I understand RPython is especially tailored for tracing JITs(http://rpython.readthedocs.io/en/latest/jit/overview.html#the-path-we-followed) and these type of JITs provide the most performance(ex. Luajit).

Thanks

**Comment by nbp** [comment]
The plan is to have both a method JIT and a tracing JIT.

A method JIT is good for handling fixed control flows, such as a constant vector used for dispatching instructions.

A tracing JIT is good for handling sparse branch usage, such as used in inline caches.

The idea is to combine both a method JIT and a tracing JIT where they are good at.  This is nothing new, the Baseline compiler of SpiderMonkey does almost the same except that our inline caches are generated after the code execution to avoid instrumenting the traced code.
