### ISSUE TITLE
Suggestion: Small language implementations to test the holyjit features

### ISSUE THREAD

**Issue by 6D65** [nbp/holyjit#13]
I think I've seen it mentioned, that the next step would be to implement a language, to see if the functionality is complete enough to implement a bigger spec(like Javascript).

I would suggest Lua(https://github.com/LuaJIT/LuaJIT)
or
Pixie(https://github.com/pixie-lang/pixie) which is a clojure variant.

Most likely Pixie would be the most useful as it's written in RPython, which should be a similar project and could potentially be a good source of inspiration.

Also, both of them seem simple languages in terms of the features and both have been implemented as JITs.

**Comment by nbp** [comment]
Thanks for the suggestions :)

While I understand the value of have a Python / Lua interpreter written in Rust, and JIT-compiled, the goal is to test in existing implementation which share similar design principles as JavaScript.  If I can avoid having to implement a language, this would add overhead to this experiment.

At the moment, I am thinking of extending @jorendorff 's test project which implements a Lisp interpreter: 
https://github.com/jorendorff/cell-gc/blob/master/lisp/src/vm.rs#L169-L453
