### ISSUE TITLE
Ideas and thoughts on runtime code optimization

### ISSUE THREAD

**Issue by carli2** [nbp/holyjit#21]
Hi,

you should read this paper: http://www.btw-2015.de/res/proceedings/Hauptband/Wiss/Haensch-Plan_Operator_Specializati.pdf
It explains how to specialize code to given data (or in holyjit's terms: turning a interpreter into a compiler) - this can be used to do very sophisticated JavaScript optimizations with a very general approach only consuming ~1000 lines of code:
 - removing JS type checks for known data
 - turning hash map lookup into index lookup
 - turn interpreters written in javascript into compilers (yes, this approach is transitive => it would even be able to turn a windows application that runs in a x86 emulator written in JS into ARM code of the target platform)

btw, i'm no longer working at Database Technology Group, but you can contact me via info@launix.de

**Comment by nbp** [comment]
Thanks for the link to the paper.

While I do not doubt the approach, I doubt that having compilation times of 100ms is acceptable at all, and especially not for JavaScript.

My focus today is on designing a proper LIR representation, to avoid the pit-falls of recompilation after a deoptimization and as a way to optimize code ahead-of-time.

**Comment by Hywan** [comment]
@nbp How to follow your progression and thoughts? I'm really interested by it.

**Comment by carli2** [comment]
Hi,

compilation times of 100ms came from LLVMs selection DAG step. I saw  
in your holyjit implementation, that you are using a very simple and  
fast opcode writer.

What I am saying with the paper is that instead of annotating 'if' and  
'while' constructs, you should annotate parts of memory as constant.  
This will automatically detect the if's and while's to optimize.

For JIT this means to annotate the memory of the code graph, or some  
bytecode, such that the compiler can create a JITed representation of  
function x(a, b) bound to a = 'some constant'.

One step further, there could be a detection mechanism that decides  
when and when not to JIT a function. (depending on the cost of jitting  
and the benefit) - so a JS function that gets called once will be  
interpreted while the execution of one and the same function multiple  
times would be jitted. Same for arbitrary other parameters: If let's  
say the expression $('.btn') is evaluated hundrets of times, this  
approach would generate a version of $(a) optimized for a='.btn'

Regards


Zitat von "Nicolas B. Pierron" <notifications@github.com>:

**Comment by carli2** [comment]
Just an other remark to the paper:

In the paper, we used annotated objects, so SQL operators were C++ classes (OperationAdd with field operand1, operand2 as well ex virtual execute()), we annotated operand1 and operand2 as constant, so the compiler pass created JITed versions of operand1->execute() and operand2->execute(), and inlined them into OperationAdd->execute().

**Comment by nbp** [comment]
@Hywan Thanks for your interest, and I would also love to see this project being used for TaguaVM.

> How to follow your progression and thoughts? I'm really interested by it.

Today, there is not much to follow unfortunately in terms of code or design. I will get back to it the next time I take some time-off (end of December) to continue the work made on HolyJit.

Today, my efforts are political and towards getting resources allocated to this project, such that it can move even when I am not taking some time-off.  The current state of the project is extremely blurry and I hope to clarify this in the upcoming weeks.

If you want to help me getting this project afloat, the best thing you can do is to speak more about it, and raise the awareness about the fact that this project exists. This project has a huge potential while having the potential of being a smaller investment if this is a community effort.

**Comment by Hywan** [comment]
To not pollute this thread, I've opened a new thread: https://github.com/nbp/holyjit/issues/22.
