### ISSUE TITLE
Will it be able to compile an interpreter written in lua or convert an interpreter written in lua with luster?

### ISSUE THREAD

**Issue by zaoqi** [nbp/holyjit#33]

**Comment by Hywan** [comment]
Is it a title, or a question? Can you provide more details please :-)?

**Comment by nbp** [comment]
I do not see any issue description. Therefore I am closing this issue.

A similar issue (#32) was opened 5 days ago, and the title got changed to suggest that `luster` could be used as a benchmark target.

While I understand that there is no forum opened for this project yet, general questions like this one could be answered by the [README.md](/nbp/holyjit/blob/master/README.md) file with statements such as `HolyJit extends the Rust compiler` and `HolyJit aims at being a JIT library`.

If you find that the [README.md](/nbp/holyjit/blob/master/README.md) does not answer your questions, I will ask you to open a clearer issue of what statements might be confusing and potentially recommend a different phrasing to make this description less confusing.

To answer these questions, HolyJit will not compile an interpreter written in Lua. However, it aims at compiling Rust code, and if you have a Lua VM written in Rust such as [luster](/kyren/luster), then transitively it could be used to compile Lua code, including an interpreter written in Lua.
