### ISSUE TITLE
Is HolyJIT named after HolyC?

### ISSUE THREAD

**Issue by tbodt** [nbp/holyjit#7]

**Comment by belst** [comment]
I think it is a pun to `Holy Sh*t`

**Comment by nbp** [comment]
This is not an issue, please reserve this question for other method of communications.
In the worst case, you can find me on irc.mozilla.org.

Then, to answer your question:
No. This project is named as a variation of the GraalVM project, and as a pun, as commented on Hacker News.
https://news.ycombinator.com/item?id=15515355
