### ISSUE TITLE
Offensive language

### ISSUE THREAD

**Issue by jewsh** [nbp/holyjit#8]
Hello,
please change the wording in https://github.com/nbp/holyjit/blob/master/lib/src/compile.rs.
As a jewish person the use of [f*inal solut*on](https://en.wikipedia.org/wiki/Final_Solution) is really upsetting to me and no doubt jewish people everywhere.

**Comment by pravic** [comment]
For those who are curious: Wikipedia. But I doubt that that line of code refers to it or means something offensive.

**Comment by cramertj** [comment]
Concern trolling isn't funny.

**Comment by nbp** [comment]
The term "final solution" used in this context only refers to expected state of the Rust code of this project.

If you prefer a different wording, feel free to contribute to this project by clicking the "edit this file" button available on github.
